web4:
  build: .
  volumes:
    - ./flashcards:/data/www/current
  ports:
    - "80:80"
    - "443:443"
  links:
   - gearmand
   - redis
gearmand:
  image: kendu/gearman
  ports: 
    - "4370:4370"
redis:
  image: redis
  ports:
    - "6379:6379"
  volumes:
    - "/data"
